import type { Metadata } from 'next';
import Sidebar from '../components/sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-screen w-full bg-gray-100">
      <Sidebar />
      <div className="flex flex-col h-full w-full ml-60 p-4">{children}</div>
    </div>
  );
}
